<template>
  <div id="kaidian">
    <el-card shadow="never">
      <div class="input-file">
        <van-cell-group>
          <van-field
            v-model="form.fr_user_name"
            :required="true"
            rows="1"
            autosize
            label="法人姓名"
            type="textarea"
            placeholder="请输入法人姓名"
          />
          <van-field
             v-model="form.fr_wx_code"
            :required="true"
            rows="1"
            autosize
            label="法人微信"
            type="textarea"
            placeholder="请输入法人微信"
          />
          <van-field
       v-model="form.enterprise_name"
            :required="true"
            rows="1"
            autosize
            label="企业名称"
            type="textarea"
            placeholder="请输入企业名称"
          />
          <van-field
           v-model="form.enterprise_code"
            :required="true"
            rows="1"
            autosize
            label="企业代码信息"
            type="textarea"
            placeholder="请输入企业代码信息"
          />
          <van-field
            v-model="form.qy_Business"
            :required="true"
            rows="1"
            autosize
            label="营业执照"
            type="textarea"
            placeholder="请输入营业执照"
          />
          <van-field
          
            v-model="form.qy_licence"
            :required="true"
            rows="1"
            autosize
            label="食品经营许可证"
            type="textarea"
            placeholder="请输入食品经营许可证"
          />
          <van-field
            v-model="form.store_door_img"
            :required="true"
            rows="1"
            autosize
            label="门面照片"
            type="textarea"
            placeholder="请输入门面照片"
          />
          <van-field
            v-model="form.store_in_img"
            :required="true"
            rows="1"
            autosize
            label="内部照片"
            type="textarea"
            placeholder="请输入内部照片"
          />
          <van-field
            v-model="form.account_name"
            :required="true"
            rows="1"
            autosize
            label="公众号名称"
            type="textarea"
            placeholder="请输入公众号名称"
          />
          <van-field
            v-model="form.account_img"
            :required="true"
            rows="1"
            autosize
            label="公众号图片"
            type="textarea"
            placeholder="请输入公众号图片"
          />
          <van-field
            v-model="form.account_info"
            :required="true"
            rows="1"
            autosize
            label="公众号描述"
            type="textarea"
            placeholder="请输入公众号描述"
          />
          <van-field
            v-model="form.mini_name"
            :required="true"
            rows="1"
            autosize
            label="小程序名称"
            type="textarea"
            placeholder="请输入小程序名称"
          />
            <van-field
            v-model="form.account_join"
            :required="true"
            rows="1"
            autosize
            label="关联微信公众号"
            type="textarea"
            placeholder="请输入关联微信公众号"
          />
            <van-field
            v-model="form.mini_img"
            :required="true"
            rows="1"
            autosize
            label="小程序图片"
            type="textarea"
            placeholder="请输入小程序图片"
          />
            <van-field
            v-model="form.mini_info"
            :required="true"
            rows="1"
            autosize
            label="小程序描述"
            type="textarea"
            placeholder="请输入小程序描述"
          />
            <van-field
            v-model="form.user_email"
            :required="true"
            rows="1"
            autosize
            label="管理员邮箱"
            type="textarea"
            placeholder="请输入管理员邮箱"
          />
            <van-field
            v-model="form.idcard_positive"
            :required="true"
            rows="1"
            autosize
            label="管理员身份证正面"
            type="textarea"
            placeholder="请输入管理员身份证正面"
          />
            <van-field
            v-model="form.idcard_unpositive"
            :required="true"
            rows="1"
            autosize
            label="管理员身份证反面"
            type="textarea"
            placeholder="请输入管理员身份证反面"
          />
            <van-field
            v-model="form.user_phone"
            :required="true"
            rows="1"
            autosize
            label="管理员手机号"
            type="textarea"
            placeholder="请输入管理员手机号"
          />
            <van-field
            v-model="form.user_wx_code"
            :required="true"
            rows="1"
            autosize
            label="管理员微信号"
            type="textarea"
            placeholder="请输入管理员微信号"
          />
        </van-cell-group>
         <div class="footer" @click="submit">保存</div>
      </div>
    </el-card>
  </div>
</template>
<script src="./index.js"></script>
<style lang="scss" scoped>
@import "index.scss";
</style>